#!/usr/bin/env python3
"""
Member 2 inference pipeline.

Loads test data, applies the trained matcher to candidate pairs,
and produces matching_results.tsv.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import joblib
import pandas as pd

from .config import cfg
from .data_loader import load_test_sources
from .feature_engineering import features_from_pairs


logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s - %(message)s",
)

log = logging.getLogger(__name__)


def run_inference(
    candidate_path: str | None = None,
    test_dir: str | None = None,
    model_path: str | None = None,
    config_path: str | None = None,
    output_path: str | None = None,
):
    """
    Run the complete matcher inference pipeline.

    Parameters
    ----------
    candidate_path:
        Candidate pairs generated by Member 1.

    test_dir:
        Test dataset directory.

    model_path:
        Trained matcher model.

    config_path:
        JSON configuration containing the decision threshold.

    output_path:
        Final matching_results.tsv path.
    """

    if candidate_path is None:
        candidate_path = str(cfg.candidate_path)

    if test_dir is None:
        test_dir = str(cfg.test_dir)

    if model_path is None:
        model_path = str(cfg.model_path)

    if config_path is None:
        config_path = str(
            Path(model_path).parent / "config.json"
        )

    if output_path is None:
        output_path = str(cfg.matching_out)

    candidate_path = Path(candidate_path)
    test_dir = Path(test_dir)
    model_path = Path(model_path)
    config_path = Path(config_path)
    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ------------------------------------------------------------------
    # Validate required files
    # ------------------------------------------------------------------

    if not candidate_path.exists():
        raise FileNotFoundError(
            f"Candidate file not found: {candidate_path}\n"
            "Run generate_candidates.py before inference."
        )

    if not model_path.exists():
        raise FileNotFoundError(
            f"Model not found: {model_path}\n"
            "Train the matcher before inference."
        )

    if not config_path.exists():
        raise FileNotFoundError(
            f"Model configuration not found: {config_path}"
        )

    # ------------------------------------------------------------------
    # Load test data
    # ------------------------------------------------------------------

    log.info("Loading test data...")

    s1, s2, s3 = load_test_sources(
        test_dir
    )

    log.info(
        "Test dataset: %,d S1, %,d S2, %,d S3",
        len(s1),
        len(s2),
        len(s3),
    )

    # ------------------------------------------------------------------
    # Load candidate pairs
    # ------------------------------------------------------------------

    log.info(
        "Loading candidates from: %s",
        candidate_path,
    )

    candidates = pd.read_csv(
        candidate_path,
        sep="\t",
        dtype=str,
    )

    required_columns = {
        "source1_entity_id",
        "candidate_entity_ids",
    }

    missing_columns = (
        required_columns
        - set(candidates.columns)
    )

    if missing_columns:
        raise ValueError(
            "Candidate file is missing required columns: "
            f"{sorted(missing_columns)}"
        )

    log.info(
        "Candidate rows loaded: %,d",
        len(candidates),
    )

    # ------------------------------------------------------------------
    # Prepare Source 2 + Source 3
    # ------------------------------------------------------------------

    s2s3 = pd.concat(
        [
            s2,
            s3,
        ],
        ignore_index=True,
    )

    # ------------------------------------------------------------------
    # Generate features
    # ------------------------------------------------------------------

    log.info(
        "Generating features for candidate pairs..."
    )

    features = features_from_pairs(
        s1,
        candidates,
        s2s3,
    )

    if features.empty:
        raise RuntimeError(
            "Feature generation produced zero candidate pairs. "
            "Refusing to create a potentially invalid submission."
        )

    log.info(
        "Generated %,d candidate feature rows",
        len(features),
    )

    # ------------------------------------------------------------------
    # Load model
    # ------------------------------------------------------------------

    log.info(
        "Loading trained model from: %s",
        model_path,
    )

    model = joblib.load(
        model_path
    )

    # ------------------------------------------------------------------
    # Load configuration
    # ------------------------------------------------------------------

    log.info(
        "Loading configuration from: %s",
        config_path,
    )

    with open(
        config_path,
        "r",
        encoding="utf-8",
    ) as file:
        config = json.load(file)

    if "threshold" not in config:
        raise KeyError(
            "Model configuration does not contain 'threshold'."
        )

    threshold = float(
        config["threshold"]
    )

    log.info(
        "Using decision threshold: %.3f",
        threshold,
    )

    # ------------------------------------------------------------------
    # Predict
    # ------------------------------------------------------------------

    feature_columns = [
        column
        for column in features.columns
        if column not in {
            "source1_entity_id",
            "candidate_id",
        }
    ]

    X = features[
        feature_columns
    ]

    log.info(
        "Scoring %,d candidate pairs...",
        len(X),
    )

    probabilities = (
        model
        .predict_proba(X)[:, 1]
    )

    features = features.copy()

    features["probability"] = probabilities

    # ------------------------------------------------------------------
    # Build predictions
    # ------------------------------------------------------------------

    log.info(
        "Applying threshold %.3f...",
        threshold,
    )

    predictions = {}

    for s1_id, group in features.groupby(
        "source1_entity_id"
    ):

        matched_ids = (
            group.loc[
                group["probability"] >= threshold,
                "candidate_id",
            ]
            .astype(str)
            .drop_duplicates()
            .tolist()
        )

        matched_ids = sorted(
            matched_ids
        )

        predictions[str(s1_id)] = (
            matched_ids
        )

    # Ensure every S1 entity is represented.

    for s1_id in s1["entity_id"].astype(str):

        if s1_id not in predictions:
            predictions[s1_id] = []

    # ------------------------------------------------------------------
    # Write matching results
    # ------------------------------------------------------------------

    rows = []

    for s1_id in sorted(
        s1["entity_id"].astype(str)
    ):

        matched_ids = predictions.get(
            s1_id,
            [],
        )

        rows.append(
            {
                "source1_entity_id": s1_id,
                "matched_entity_ids": ",".join(
                    matched_ids
                ),
            }
        )

    output = pd.DataFrame(
        rows
    )

    output.to_csv(
        output_path,
        sep="\t",
        index=False,
    )

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    entities_with_matches = sum(
        bool(ids)
        for ids in predictions.values()
    )

    singleton_entities = (
        len(predictions)
        - entities_with_matches
    )

    total_matched_ids = sum(
        len(ids)
        for ids in predictions.values()
    )

    log.info("")
    log.info("=" * 70)
    log.info("INFERENCE SUMMARY")
    log.info("=" * 70)
    log.info(
        "Total S1 entities: %,d",
        len(predictions),
    )
    log.info(
        "Entities with matches: %,d",
        entities_with_matches,
    )
    log.info(
        "Singleton / no-match entities: %,d",
        singleton_entities,
    )
    log.info(
        "Total matched IDs: %,d",
        total_matched_ids,
    )
    log.info(
        "Threshold: %.3f",
        threshold,
    )
    log.info(
        "Output: %s",
        output_path,
    )
    log.info("=" * 70)

    return output


if __name__ == "__main__":
    run_inference()
